### ISSUE TITLE
Notify teacher when they are inviting non paid co teacher

### ISSUE THREAD

**Issue by komalahuwalia** [peblio/app#885] opened 2021-03-10 13:20 UTC
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment] 2021-07-02 12:28
duplicate of #869

**Closed by MathuraMG** 2021-07-02 12:28 UTC
