### ISSUE TITLE
You can't use tab inside a text area 

### ISSUE THREAD

**Issue by estherhersh** [peblio/app#430] opened 2018-09-06 21:05 UTC
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug:

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by MathuraMG** [comment] 2018-12-05 08:14
Focus leaves the draft-js component on tab. 
Need to look into the behaviour of the [onTab](https://jpuri.github.io/react-draft-wysiwyg/#/docs?_k=jjqinp) callback in wysiwyg-draft-js component

**Comment by MathuraMG** [comment] 2020-03-12 09:55
Duplicate of #658

**Closed by MathuraMG** 2020-03-12 09:55 UTC
Labels: bug
